export const LOAD_PRACTITIONER_FROM_SERVER = 'LOAD_PRACTITIONER_FROM_SERVER';
export const SELECT_PRACTITIONER = 'SELECT_PRACTITIONER';
export const LOAD_CLINICS_FROM_SERVER = 'LOAD_CLINICS_FROM_SERVER';
export const MOUSE_ENTER_CLINIC = 'MOUSE_ENTER_CLINIC';
export const MOUSE_LEAVE_CLINIC = 'MOUSE_LEAVE_CLINIC';
export const SELECT_CLINIC = 'SELECT_CLINIC';