export const LOAD_PRACTITIONER_FROM_SERVER = 'LOAD_PRACTITIONER_FROM_SERVER';
export const SELECT_PRACTITIONER = 'SELECT_PRACTITIONER';
export const LOAD_CLINICS_FROM_SERVER = 'LOAD_CLINICS_FROM_SERVER';
export const MOUSE_ENTER_CLINIC = 'MOUSE_ENTER_CLINIC';
export const MOUSE_LEAVE_CLINIC = 'MOUSE_LEAVE_CLINIC';
export const SELECT_CLINIC = 'SELECT_CLINIC';
export const SELECT_TIME = 'SELECT_TIME';
export const INITIAL_TIME = 'INITIAL_TIME';
export const DATEPICKER_ON_SELECT = 'DATEPICKER_ON_SELECT';
export const OPEN_DATEPICKER_DIALOG = 'OPEN_DATEPICKER_DIALOG';
export const CLOSE_DATEPICKER_DIALOG = 'CLOSE_DATEPICKER_DIALOG';
export const TEST_ACTION1 = 'TEST_ACTION1';

export const CURRENT_BOOKING_SET_CALENDAR = 'CURRENT_BOOKING_SET_CALENDAR';
export const CURRENT_BOOKING_SET_PATIENT = 'CURRENT_BOOKING_SET_PATIENT';
export const CURRENT_BOOKING_SUBMIT = 'CURRENT_BOOKING_SUBMIT';