export const LOAD_PRACTITIONER_FROM_SERVER = 'LOAD_PRACTITIONER_FROM_SERVER';
export const SELECT_PRACTITIONER = 'SELECT_PRACTITIONER';
export const LOAD_CLINICS_FROM_SERVER = 'LOAD_CLINICS_FROM_SERVER';